USE ezeeitco_EZEE_INVOICE;

ALTER TABLE EZEE_INVOICE CHANGE TAXABLE MANUAL_TAX BOOLEAN;

ALTER TABLE EZEE_INVOICE ADD INVOICE_DATE DATE NULL;

ALTER TABLE EZEE_CONFIGURATION ADD DEFAULT_DEBT_AGE_RULE VARCHAR(200) NULL;

ALTER TABLE EZEE_CONFIGURATION ADD DEFAULT_INVOICE_SUPPLIER VARCHAR(200) NULL;

ALTER TABLE EZEE_CONFIGURATION ADD DEFAULT_MANUAL_TAX BOOLEAN NULL DEFAULT TRUE;