USE EZEE;

ALTER TABLE EZEE_PAYER ADD CONTACT VARCHAR(100) NULL;
ALTER TABLE EZEE_PAYEE ADD CONTACT VARCHAR(100) NULL;

CREATE TABLE IF NOT EXISTS EZEE_PROJECT (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(200) NOT NULL,
	START_DATE VARCHAR(10) NULL,
	END_DATE VARCHAR(10) NULL,
	ADDRESS_LINE_1 VARCHAR(200) NULL,
	ADDRESS_LINE_2 VARCHAR(200) NULL,
	SUBURB VARCHAR(50) NULL,
	CITY VARCHAR(50) NULL,
	STATE VARCHAR(10) NULL,
	POST_CODE VARCHAR(10) NULL,
	PHONE VARCHAR(20) NULL,
	FAX VARCHAR(20) NULL,
	EMAIL VARCHAR(50) NULL,
	CONTACT VARCHAR(100) NULL,
	CREATED VARCHAR(10) NULL,
	UPDATED VARCHAR(10) NULL,
	PRIMARY KEY(ID),
	UNIQUE(NAME)
);

CREATE TABLE IF NOT EXISTS EZEE_PROJECT_ITEM (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(200) NOT NULL,
	PROJECT_ID INTEGER NULL,
	CREATED VARCHAR(10) NULL,
	UPDATED VARCHAR(10) NULL,
	FOREIGN KEY (PROJECT_ID) REFERENCES EZEE_PROJECT(ID),
	PRIMARY KEY(ID),
	UNIQUE(NAME, PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS EZEE_PROJECT_ITEM_TO_RESOURCE_MAPPING (
	ITEM_ID INTEGER NOT NULL,
	RESOURCE_ID INTEGER NOT NULL,
	FOREIGN KEY (ITEM_ID) REFERENCES EZEE_PROJECT_ITEM(ID),
	FOREIGN KEY (RESOURCE_ID) REFERENCES EZEE_PAYEE(ID),
	PRIMARY KEY(ITEM_ID,RESOURCE_ID)
);

CREATE TABLE IF NOT EXISTS EZEE_PROJECT_ITEM_DETAIL (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(200) NOT NULL,
	ITEM_TYPE VARCHAR(10) NOT NULL,
	AMOUNT DECIMAL(10,2) NOT NULL,
	TAX DECIMAL(10,2) NOT NULL,
	ITEM_ID INTEGER NULL,
	CREATED VARCHAR(10) NULL,
	UPDATED VARCHAR(10) NULL,
	FOREIGN KEY (ITEM_ID) REFERENCES EZEE_PROJECT_ITEM(ID),
	PRIMARY KEY(ID),
	UNIQUE(DESCRIPTION, ITEM_ID)
);

CREATE TABLE IF NOT EXISTS EZEE_PROJECT_PAYMENT (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	PAYMENT_DATE VARCHAR(10) NOT NULL,
	PAYMENT_TYPE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	AMOUNT DECIMAL(10,2) NOT NULL,
	TAX DECIMAL(10,2) NOT NULL,
	CHEQUE_NUMBER VARCHAR(30) NULL,
	ITEM_ID INTEGER NULL,
	CREATED VARCHAR(10) NULL,
	UPDATED VARCHAR(10) NULL,
	FOREIGN KEY (ITEM_ID) REFERENCES EZEE_PROJECT_ITEM(ID),
	PRIMARY KEY(ID)
);