USE EZEE;

ALTER TABLE EZEE_CONFIGURATION ADD LICENSEE VARCHAR(200) NULL;

ALTER TABLE EZEE_PAYEE ADD SOURCE VARCHAR(50) NOT NULL DEFAULT 'EzeeInvoiceWeb';

ALTER TABLE EZEE_CONFIGURATION ADD DEFAULT_REVERSE_TAX BOOLEAN NULL DEFAULT FALSE;

ALTER TABLE EZEE_CONFIGURATION ADD DEFAULT_SHOW_PAID BOOLEAN NULL DEFAULT TRUE;