USE EZEE;

ALTER TABLE EZEE_PAYEE DROP COLUMN SOURCE;

ALTER TABLE EZEE_PAYEE ADD PAYEE_TYPE VARCHAR(50) NOT NULL DEFAULT 'Supplier';

RENAME TABLE EZEE_INVOICE_TO_PAYEE_MAPPING TO EZEE_INVOICE_TO_SUPPLIER_MAPPING;

RENAME TABLE EZEE_PROJECT_ITEM_TO_RESOURCE_MAPPING TO EZEE_PROJECT_ITEM_TO_CONTRACTOR_MAPPING;