USE ezeeitco_EZEE_INVOICE;

INSERT INTO EZEE_CONFIGURATION (VERSION, INVOICE_TAX_RATE) VALUES ('0.0.1-SNAPSHOT', 0.1);
UPDATE EZEE_CONFIGURATION SET DEFAULT_DEBT_AGE_RULE = '2M' WHERE VERSION = '0.0.1-SNAPSHOT';

INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('7D', FALSE, 7, 'days');
INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('1M', TRUE, 1, 'months');
INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('2M', TRUE, 2, 'months');
INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('3M', TRUE, 3, 'months');