USE ezeeitco_EZEE_INVOICE;

INSERT INTO EZEE_CONFIGURATION (VERSION, INVOICE_TAX_RATE) VALUES ('0.0.1-SNAPSHOT', 0.1);

--INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('30D', TRUE, 30, 'days');
--INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('60D', TRUE, 60, 'days');
--INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('90D', TRUE, 90, 'days');
INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('1M', TRUE, 1, 'months');
INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('2M', TRUE, 2, 'months');
INSERT INTO EZEE_DEBT_AGE_RULE (NAME, EOM, INTERVAL_LENGTH, INTERVAL_TYPE) VALUES ('3M', TRUE, 3, 'months');